nota1 = float(input('Primeira Nota:'))
nota2 = float(input('Segunda Nota:'))
nota3 = float(input('Terceira Nota:'))
nota4 = float(input('Quarta Nota:'))
soma= (nota1 + nota2 + nota3 + nota4)
print('A soma entre {},{},{} e {} e igual a {}:'.format(nota1,nota2,nota3,nota4,soma))

nota1 = int(input('Primera Nota:'))
nota2 = int(input('Segunda Nota:'))
nota3 = int(input('Terceira nota:'))
nota4:  int(input('Quarta nota:'))
Sub= (nota1 - nota2 - nota3 - nota4)
print('A subtracao entre {},{},{} e {} e igual a {}'.format(nota1,nota2,nota3,nota4,Sub))

nota1 =float(input('Primeira Nota:'))
nota2 =float(input('Segunda Nota:'))
nota3 =float(input('Terceira Nota:'))
nota4 =float(input('Quarta nota:'))
media = (nota1+nota2+nota3+nota4 / 4)
print('A media entre {},{},{} e {} e igual a {}.'.format(nota1,nota2,nota3,nota4,media))